version: '2'
services:
  go-chat:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/andrew-boutin/go-chat
    working_dir: /go/src/github.com/andrew-boutin/go-chat
    command: [sh, -c, "glide install && go run main.go"]
  redis:
    image: redis:alpine